services:
  transactions:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/transactions
    depends_on:
      - postgres

  postgres:
    image: postgres:13.7
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: